#! /usr/bin/sh

if [ $# != 1 ]; then
	echo "Must have exactly 1 arguments"
	exit 1
fi

for i in $(seq 1 "$1")
do
  if [ ! -d "cp$i" ]
  then
    cp -r cp$((i-1)) "cp$i"
  fi
done

mv cp cptemp
mv "cp$1" cp
mv cptemp "cp$1"

